# import and installation

In [1]:
import numpy as np
import time

In [2]:
arr1=np.array([1,2,3,4,5,6])
print(arr1,type(arr1))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [3]:
# execution performance
size=10_000_000
# python list
start=time.time()
my_list=list(range(size))
sq_list=[x ** 2 for x in my_list]
end=time.time()
print(f"Time for python list is = {end - start} seconds")

# numpy array
arr2=np.array(my_list)
start=time.time()
sq_arr=arr2 ** 2
end=time.time()
print(f"Time for numpy array is = {end - start} seconds")

Time for python list is = 4.382063865661621 seconds
Time for numpy array is = 0.37302327156066895 seconds


In [4]:
import sys

list_total = sys.getsizeof(my_list) + sum(sys.getsizeof(i) for i in my_list)
print("Actual Python list memory:", list_total)
# print(f"Python list size = {sys.getsizeof(my_list)} bytes")


print(f"Numpy array  size = {arr2.nbytes} bytes")


Actual Python list memory: 360000056
Numpy array  size = 80000000 bytes


# one dimensional array

In [5]:
# creating numpy array
arr3=np.array([3,4,5,6,7,8,9])
print(arr3,type(arr3),arr3.dtype)

[3 4 5 6 7 8 9] <class 'numpy.ndarray'> int64


In [6]:
arr3=np.array([3,4,5,6,7,8,9,"ali"])
print(arr3,type(arr3),arr3.dtype)

['3' '4' '5' '6' '7' '8' '9' 'ali'] <class 'numpy.ndarray'> <U21


In [7]:
# give the dimension of array (row ,column) value
arr3.shape

(8,)

# 2 D (Two dimensional array)

In [8]:
arr=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print(arr.dtype)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)


In [9]:
# create we want to create array by giving dimebsions and pre filled with zero value
arr9=np.zeros((2,3) ,dtype="int64")
print(arr9,arr9.shape)
# create we want to create array by giving dimebsions and pre filled with one value

arr9=np.ones((2,3) ,dtype="int64")
print(arr9,arr9.shape)

arr9=np.full((3,4) ,100) # prefilled with particular val
print(arr9,arr9.shape)

arr9=np.eye(3,)    # identity matrix
print(arr9,arr9.shape)

arr9=np.arange(1,11)    # range elements
print(arr9,arr9.shape)

arr9=np.linspace(1,100,4)
print(arr9,arr9.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.  34.  67. 100.] (4,)


# proppertise of arrays

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
# converting or changing data type second method
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.shape)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] (3, 3)


# important operations on numpy arrays

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped=arr.reshape(3,2)
print(reshaped,reshaped.shape)

flattened=arr.flatten()# 2d to 1d array
print(flattened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [12]:
# indexing on numpy array
arr=np.array([1,2,3])
print(arr[0],arr.shape)

# 2d array indexing
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1[0][1],arr1.shape)
# fancing indexing
idx=[0,1,2]
print(arr[idx])
# boolean indexing
print(arr[arr > 2])
print(arr[arr % 2 == 0])

# slicing on an array
arr7=np.array([1,2,3,4,5])
print(arr7[1:4])
print(arr7[1:])
print(arr7[:4])
print(arr7[::-1])

1 (3,)
2 (2, 3)
[1 2 3]
[3]
[2]
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[5 4 3 2 1]


In [13]:
# copy vs View
num=[1,2,3,4,5]
sublist=num[1:3]
print(sublist)
sublist[0]=200
print(sublist)
print(num)

#in numpy array
arr2=np.array([1,2,3,4,5])
sublist=arr2[1:3].copy()
print(sublist)
sublist[0]=200
print(sublist)
print(arr2)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[1 2 3 4 5]


# common data types in numpy array

In [14]:
arr=np.array([1,2,3,4,5,6])
print(arr,arr.dtype)

arr=np.array([1,2,3,4.,5,6])
print(arr,arr.dtype)

arr=np.array([1,2,3,4.,5,6,"Prime"])
print(arr,arr.dtype)

arr=np.array([2+3J])
print(arr,arr.dtype)

[1 2 3 4 5 6] int64
[1. 2. 3. 4. 5. 6.] float64
['1' '2' '3' '4.0' '5' '6' 'Prime'] <U32
[2.+3.j] complex128


In [15]:
arr=np.array(["prime", {1,2,3}, 3.14])
print(arr,arr.dtype)

['prime' {1, 2, 3} 3.14] object


# multidimenstional array

In [25]:
arr2=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr2)
print(arr2[0:2,1:2])

print(np.sum(arr2))

sum_of_columns=np.sum(arr2,axis=0)
print(sum_of_columns)

sum_of_columns=np.sum(arr2,axis=1)
print(sum_of_columns)

print(arr2[0:,0:1])


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[2]
 [2]]
18
[3 6 9]
[6 6 6]
[[1]
 [1]
 [1]]


In [56]:
#3 D Array
arr2=np.array([[[1,2,3],[1,2,4],[1,2,3]],
              [[1,2,3],[1,2,4],[1,2,3]],
              [[1,2,3],[1,2,4],[1,2,3]]])
print(arr2)

print(np.sum(arr2))
# indexing
print(arr2[0,2,2])
print(arr2[0,2,1])

# slicing

print(arr2[:,:,1:2])

print(arr2[:,1:2,:])

arr2[:,1:2,:]=90
print(arr2)

[[[1 2 3]
  [1 2 4]
  [1 2 3]]

 [[1 2 3]
  [1 2 4]
  [1 2 3]]

 [[1 2 3]
  [1 2 4]
  [1 2 3]]]
57
3
2
[[[2]
  [2]
  [2]]

 [[2]
  [2]
  [2]]

 [[2]
  [2]
  [2]]]
[[[1 2 4]]

 [[1 2 4]]

 [[1 2 4]]]
[[[ 1  2  3]
  [90 90 90]
  [ 1  2  3]]

 [[ 1  2  3]
  [90 90 90]
  [ 1  2  3]]

 [[ 1  2  3]
  [90 90 90]
  [ 1  2  3]]]


In [57]:
arr2=np.array([[1,2,3]])
print(arr2 **2)
print(arr2 +2)


[[1 4 9]]


In [64]:
arr2=np.array([[1,2,3],[2,4,6],[2,4,6]])
print(arr2,arr2.shape)

arr3=np.array([[1,2,3],[2,4,6]])
print(arr3,arr3.shape)

print(arr2+arr3)


[[1 2 3]
 [2 4 6]
 [2 4 6]] (3, 3)
[[1 2 3]
 [2 4 6]] (2, 3)


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [69]:
# normalization
arr=np.array([[1,2],[3,4]])
print(arr)
mean=np.mean(arr)
std_val=np.std(arr)

print((arr - mean)/std_val)

[[1 2]
 [3 4]]
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


# Important Numpy Functions

In [73]:
# aggrigation function
arr2=np.array([[1,2,3]])
print(np.sum(arr2))
print(np.prod(arr2))
print(np.min(arr2))
print(np.max(arr2))
print(np.mean(arr2))
print(np.median(arr2))
print(np.std(arr2))
print(np.argmin(arr2))
print(np.argmax(arr2))
print(np.var(arr2))


6
6
1
3
2.0
2.0
0.816496580927726
0
2
0.6666666666666666


In [74]:
# power function
arr2=np.array([[1,2,3]])
print(np.square(arr2))
print(np.sqrt(arr2))
print(np.power(arr2,3))

[[1 4 9]]
[[1.         1.41421356 1.73205081]]
[[ 1  8 27]]


In [76]:
# log and exponentional function
arr2=np.array([[1,2,3]])
print(np.log(arr2))   #natural log
print(np.log10(arr2))   
print(np.log2(arr2))   
print(np.exp(arr2))   

[[0.         0.69314718 1.09861229]]
[[0.         0.30103    0.47712125]]
[[0.        1.        1.5849625]]
[[ 2.71828183  7.3890561  20.08553692]]


In [83]:
# rounding
arr2=np.array([[1,4,4,4-4,-4,2,2,3,3,3]])
print(np.round(3.14))
print(np.ceil(3.9)) #round up
print(np.floor(3.2))  # roud down
print(np.floor(3.2))  # cut the .val



print(np.unique(arr2))
print(np.sort(arr2))
print(np.abs(arr2))

3.0
4.0
3.0
3.0
[-4  0  1  2  3  4]
[[-4  0  1  2  2  3  3  3  4  4]]
[[1 4 4 0 4 2 2 3 3 3]]
